### ISSUE TITLE
Switch-Case-Statements with negative number reports a missing whitspace

### ISSUE THREAD

**Issue by andygrunwald** [typo3-ci/TYPO3SniffPool#29] opened 2014-08-11 22:08 UTC
I got a mail from Jigal van Hemert with a bug description:

```
switches with something like "case -1:" complain that there must a space between the operator and the value
```

Please check if this is a valid bug. If yes, just fix it :)

**Comment by Konafets** [comment] 2015-04-26 20:37
Duplicate of #47.

**Closed by Konafets** 2015-04-26 20:37 UTC
Labels: bug, question
